### ISSUE TITLE
Hello com.huawei.works is not in directory app

### ISSUE THREAD

**Issue by Archer456** [Louis-me/appium#1]
我git clone项目 pycharm打开了。看了下相关doc。
看到runner.py  是你当前
 _initApp["appPackage"] = "com.huawei.works"  这个app的
但在项目app目录下 并未找到该apk 
![default](https://user-images.githubusercontent.com/18392901/34708955-24c73cd0-f550-11e7-92a3-c36a9124b7dc.png)

**Comment by Louis-me** [comment]
涉及到公司内部的app,被我删除
