### ISSUE TITLE
可以跑起来，但用例一个都没有执行，是哪里的问题？

### ISSUE THREAD

**Issue by rain-beaver** [Louis-me/appium#13]
----------------------------------------------------------------------
Ran 1 test in 25.788s

OK
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1524723108669 (14:11:48 GMT+0800 (中国标准时间))
[debug] [W3C] Received response: null
[debug] [W3C] But deleting session, so not returning
[debug] [W3C] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/5f9d0fba-06ae-4fa8-9736-eeacd76a52c5 200 729 ms - 76
[HTTP] 
--------- countDate------
------read-------
{'versionCode': '40', 'versionName': '1.4.0', 'packingTime': '2017/12/4 13:00', 'sum': 1, 'pass': 1, 'fail': 0}
{'versionCode': '40', 'versionName': '1.4.0', 'packingTime': '2017/12/4 13:00', 'sum': 1, 'pass': 1, 'fail': 0}
------read-------
{'versionCode': '40', 'versionName': '1.4.0', 'packingTime': '2017/12/4 13:00', 'sum': 1, 'pass': 1, 'fail': 0, 'testDate': '2018-04-26 14:11:48', 'testSumDate': '25秒'}
------read-------
[{'phone_name': 'Meizu_PRO_android_7.0.0', 'pass': 1, 'fail': 0, 'device': 'M96GSEQ2XUJ7R'}]
[{'step': '允许应用获得对应权限\n跳过欢迎页\n滑动第一次\n滑动第二次\n立即体验\n跳转到账户页\n输入手机号\n输入密码\n登录按钮\n', 'checkStep': '检测是否登录成功,用户昵称是否展示\n', 'result': '通过', 'id': 'test001', 'title': '登录', 'caseName': 'testLoging', 'phoneName': 'Meizu_PRO_android_7.0.0', 'msg': '', 'info': '正常打开App'}]
------read-------
[{'step': '允许应用获得对应权限\n跳过欢迎页\n滑动第一次\n滑动第二次\n立即体验\n跳转到账户页\n输入手机号\n输入密码\n登录按钮\n', 'checkStep': '检测是否登录成功,用户昵称是否展示\n', 'result': '通过', 'id': 'test001', 'title': '登录', 'caseName': 'testLoging', 'phoneName': 'Meizu_PRO_android_7.0.0', 'msg': '', 'info': '正常打开App'}]

Process finished with exit code 0

**Comment by Louis-me** [comment]
代码已经优化，changlog中已经说明了，此次删除了多余代码，用的雷电模拟器进行的测试，手上没有真机
