### ISSUE TITLE
ImportError: No module named 'TestCase'

### ISSUE THREAD

**Issue by Archer456** [Louis-me/appium#2]
![default](https://user-images.githubusercontent.com/18392901/34709600-d152fc76-f552-11e7-9d04-98441da797b8.png)

from TestCase.HomeTest import HomeTest
from TestCase.ContactTest import ContactTest
from TestCase.CardsTest import CardsTest
from TestCase.MeTest import MeTest
from TestCase.HistoryTest import HistoryTest
from TestCase.TeamTest import TeamTest
from TestCase.TestWeiQunTest import TestWeiQunTest

这里的TestCase 要改成项目里的testcase目录名吧?

**Comment by Louis-me** [comment]
嗯，从另外一台电脑靠过来的。。没有注意，修改过了
