### ISSUE TITLE
为何要每次都重新安装uiautomator2都两个应用？

### ISSUE THREAD

**Issue by Archer456** [Louis-me/appium#4]
BaseInit.py 中看到

# 每次都重新安装uiautomator2都两个应用
os.popen("adb uninstall io.appium.uiautomator2.server.test")
os.popen("adb uninstall io.appium.uiautomator2.server")
os.popen("adb install -r "+PATH("../app/appium-uiautomator2-server-v0.1.9.apk"))
os.popen("adb install -r "+PATH("../app/appium-uiautomator2-server-debug-androidTest.apk"))

本地环境查出
cmd@TR:~$ sudo find / -name "*appium-uiautomator2-server*"
[sudo] cmd 的密码： 
^C
cmd@TR:~$ sudo find /opt/nodejs/ -name "*appium-uiautomator2-server*"
/opt/nodejs/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-v0.1.8.apk
/opt/nodejs/lib/node_modules/appium/node_modules/appium-uiautomator2-driver/uiautomator2/appium-uiautomator2-server-debug-androidTest.apk
/opt/nodejs/lib/node_modules/appium/node_modules/appium-uiautomator2-server
/opt/nodejs/lib/node_modules/appium/node_modules/appium-uiautomator2-server/appium-uiautomator2-server.iml

cmd@TR:~$ appium -v
1.7.1

为何要每次都重新安装uiautomator2都两个应用？

**Comment by Louis-me** [comment]
我主要用的是uiautomator2,在使用过程中，发现经常启动超时，现在的临时解决方案是第一次连接都会重新安装uiautomator2那两个包
