### ISSUE TITLE
android getphoneinfo 方法好像是针对真机的关键词，不通用

### ISSUE THREAD

**Issue by Archer456** [Louis-me/appium#5]
![image](https://user-images.githubusercontent.com/18392901/34925972-9c47af42-f9e7-11e7-92ab-c082c34e1909.png)
我用的genymotion模拟器   发现getphoneinfo 获取到的信息的查找关键词 和 模拟器的对应不上。

那也有可能  没有考虑其他miui  huawei   氢os 等定制化的？

**Comment by Louis-me** [comment]
暂时没有测试过。。这里代码你可以自己优化
