### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by LYJHON** [Louis-me/appium#7]
appium --session-override  -p 4778 -bp 4777 -U 74a52861c958
--------start_win_server-------------
--------start_win_server-------------
[Appium] Welcome to Appium v1.7.1
[Appium] Non-default server args:
[Appium]   port: 4778
[Appium]   bootstrapPort: 4777
[Appium]   sessionOverride: true
[Appium]   udid: 74a52861c958
[Appium] Deprecated server args:
[Appium]   -U,--udid => --default-capabilities '{"udid":"74a52861c958"}'
[Appium] Default capabilities, which will be added to each request unless overridden by desired capabilities:
[Appium]   udid: '74a52861c958'
[Appium] Appium REST http interface listener started on 0.0.0.0:4778
[HTTP] --> GET /wd/hub/status {}
[debug] [MJSONWP] Calling AppiumDriver.getStatus() with args: []
[debug] [MJSONWP] Responding to client with driver.getStatus() result: {"build":{"version":"1.7.1","revision":null}}
-------win_server_ 成功--------------
----runnerPool------
{'devices': '74a52861c958', 'port': '4778', 'bport': '4777', 'systemPort': '4774'}
adb -s 74a52861c958 shell cat /system/build.prop 
[HTTP] <-- GET /wd/hub/status 200 31 ms - 83 
{'release': '4.4.4', 'model': 'Che1-CL20', 'brand': 'Honor', 'device': 'Che1'}
['testLogin']
[HTTP] --> POST /wd/hub/session {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"android"}},"desiredCapabilities":{"appPackage":"com.jhqc.pxsj","appActivity":"com.jhqc.pxsj.activity.launch.LaunchActivity","udid":"74a52861c958","platformVersion":"4.4.4","platformName":"android","automationName":"uiautomator2","deviceName":"74a52861c958","noReset":"True","noSign":"True","unicodeKeyboard":"True","resetKeyboard":"True","systemPort":"4774"}}
[debug] [MJSONWP] Calling AppiumDriver.createSession() with args: [{"appPackage":"com.jhqc.pxsj","appActivity":"com.jhqc.pxsj.activity.launch.LaunchActivity","udid":"74a52861c958","platformVersion":"4.4.4","platformName":"android","automationName":"uiautomator2","deviceName":"74a52861c958","noReset":"True","noSign":"True","unicodeKeyboard":"True","resetKeyboard":"True","systemPort":"4774"},null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"android"}}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1517387363268 (16:29:23 GMT+0800 (中国标准时间))
[Appium] Creating new AndroidUiautomator2Driver (v0.6.5) session
[Appium] Capabilities:
[Appium]   appPackage: 'com.jhqc.pxsj'
[Appium]   appActivity: 'com.jhqc.pxsj.activity.launch.LaunchActivity'
[Appium]   udid: '74a52861c958'
[Appium]   platformVersion: '4.4.4'
[Appium]   platformName: 'android'
[Appium]   automationName: 'uiautomator2'
[Appium]   deviceName: '74a52861c958'
[Appium]   noReset: 'True'
[Appium]   noSign: 'True'
[Appium]   unicodeKeyboard: 'True'
[Appium]   resetKeyboard: 'True'
[Appium]   systemPort: '4774'
[BaseDriver] Capability 'noReset' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'unicodeKeyboard' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'resetKeyboard' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] Capability 'noSign' changed from string to boolean. This may cause unexpected behavior
[BaseDriver] The following capabilities were provided, but are not recognized by appium: systemPort.
[BaseDriver] Session created with session id: 97457b5d-c529-4c18-afd9-376a7c4eed76
[debug] [AndroidDriver] Getting Java version
[AndroidDriver] Java version is: 1.8.0_31
[ADB] Checking whether adb is present
[ADB] Using adb.exe from F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe
[AndroidDriver] Retrieving device list
[debug] [ADB] Trying to find a connected android device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[AndroidDriver] Using device: 74a52861c958
[ADB] Checking whether adb is present
[ADB] Using adb.exe from F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe
[debug] [ADB] Setting device id to 74a52861c958
[AndroidDriver] No app sent in, not parsing package/activity
[ADB] Getting device platform version
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","getprop","ro.build.version.release"]
[debug] [ADB] Current device property 'ro.build.version.release': 4.4.4
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","wm","size"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","getprop","ro.product.model"]
[debug] [ADB] Current device property 'ro.product.model': Che1-CL20
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","getprop","ro.product.manufacturer"]
[debug] [ADB] Current device property 'ro.product.manufacturer': HUAWEI
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","am","force-stop","io.appium.uiautomator2.server"]
[ADB] Checking whether aapt is present
[ADB] Using aapt.exe from F:\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\25.0.2\aapt.exe
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","pm","list","packages","io.appium.uiautomator2.server"]
[debug] [ADB] App is installed
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
[debug] [ADB] App is installed
[debug] [ADB] Getting package info for io.appium.uiautomator2.server
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","dumpsys","package","io.appium.uiautomator2.server"]
[debug] [UiAutomator2] Server installed but version 0.1.9 instead of 0.1.8. Re-installing
[debug] [ADB] Uninstalling io.appium.uiautomator2.server
[debug] [ADB] Getting install status for io.appium.uiautomator2.server
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","pm","list","packages","io.appium.uiautomator2.server"]
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","am","force-stop","io.appium.uiautomator2.server"]
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","uninstall","io.appium.uiautomator2.server"]
[debug] [ADB] ADB command output: Success
[ADB] io.appium.uiautomator2.server was successfully uninstalled
[debug] [ADB] Uninstalling io.appium.uiautomator2.server.test
[debug] [ADB] Getting install status for io.appium.uiautomator2.server.test
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","pm","list","packages","io.appium.uiautomator2.server.test"]
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","am","force-stop","io.appium.uiautomator2.server.test"]
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","uninstall","io.appium.uiautomator2.server.test"]
[debug] [ADB] ADB command output: Success
[ADB] io.appium.uiautomator2.server.test was successfully uninstalled
[debug] [ADB] Checking app cert for C:\Users\PC\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk.
[debug] [ADB] App already signed.
[debug] [ADB] Zip-aligning 'C:\Users\PC\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-v0.1.8.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from F:\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\25.0.2\zipalign.exe
[debug] [ADB] Zip-aligning apk.
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","install","-r","C:\\Users\\PC\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-v0.1.8.apk"]
[UiAutomator2] Installed UiAutomator2 server apk
[debug] [ADB] Checking app cert for C:\Users\PC\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-debug-androidTest.apk.
[debug] [ADB] App already signed.
[debug] [ADB] Zip-aligning 'C:\Users\PC\AppData\Roaming\npm\node_modules\appium\node_modules\appium-uiautomator2-driver\uiautomator2\appium-uiautomator2-server-debug-androidTest.apk'
[ADB] Checking whether zipalign is present
[ADB] Using zipalign.exe from F:\android-sdk_r24.4.1-windows\android-sdk-windows\build-tools\25.0.2\zipalign.exe
[debug] [ADB] Zip-aligning apk.
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","install","-r","C:\\Users\\PC\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-uiautomator2-driver\\uiautomator2\\appium-uiautomator2-server-debug-androidTest.apk"]
[UiAutomator2] Installed UiAutomator2 server test apk
[debug] [UiAutomator2] Waiting up to 20000ms for instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' to be available
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","pm","list","instrumentation"]
[debug] [UiAutomator2] Instrumentation 'io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner' available
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","wait-for-device"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","echo","ping"]
[debug] [Logcat] Starting logcat capture
[debug] [AndroidDriver] Enabling Unicode keyboard support
[debug] [AndroidDriver] Pushing unicode ime to device...
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","install","C:\\Users\\PC\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-android-ime\\bin\\UnicodeIME-debug.apk"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","settings","get","secure","default_input_method"]
[debug] [AndroidDriver] Unsetting previous IME io.appium.android.ime/.UnicodeIME
[debug] [AndroidDriver] Setting IME to 'io.appium.android.ime/.UnicodeIME'
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","ime","enable","io.appium.android.ime/.UnicodeIME"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","ime","set","io.appium.android.ime/.UnicodeIME"]
[debug] [AndroidDriver] Pushing settings apk to device...
[debug] [ADB] Uninstalling and re-installing 'io.appium.settings'
[debug] [ADB] Uninstalling io.appium.settings
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","pm","list","packages","io.appium.settings"]
[debug] [ADB] App is installed
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","am","force-stop","io.appium.settings"]
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","uninstall","io.appium.settings"]
[debug] [ADB] ADB command output: Success
[ADB] io.appium.settings was successfully uninstalled
[debug] [ADB] Getting install status for io.appium.settings
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","pm","list","packages","io.appium.settings"]
[debug] [ADB] App is not installed
[debug] [ADB] App 'C:\Users\PC\AppData\Roaming\npm\node_modules\appium\node_modules\io.appium.settings\app\build\outputs\apk\settings_apk-debug.apk' not installed. Installing
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","install","C:\\Users\\PC\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\io.appium.settings\\app\\build\\outputs\\apk\\settings_apk-debug.apk"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","getprop","ro.build.version.sdk"]
[debug] [ADB] Current device property 'ro.build.version.sdk': 19
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","dumpsys","package","io.appium.settings"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","ps"]
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","am","start","-W","-n","io.appium.settings/.Settings","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","settings","put","secure","mock_location","1"]
[debug] [AndroidDriver] Pushing unlock helper app to device...
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","install","C:\\Users\\PC\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\appium-unlock\\bin\\unlock_apk-debug.apk"]
[debug] [UiAutomator2] Forwarding UiAutomator2 Server port 6790 to 4774
[debug] [ADB] Forwarding system: 4774 to device: 6790
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","forward","tcp:4774","tcp:6790"]
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","dumpsys","window"]
[AndroidDriver] Screen already unlocked, doing nothing
[debug] [AndroidDriver] Extracting strings from apk null null C:\Users\PC\AppData\Local\Temp\com.jhqc.pxsj
[debug] [ADB] Extracting strings for language: default
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","getprop","persist.sys.language"]
[debug] [ADB] Current device property 'persist.sys.language': zh
[debug] [ADB] No strings.xml for language 'zh', getting default strings.xml
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","rm","-rf","/data/local/tmp/strings.json"]
[debug] [UiAutomator2] No app capability. Assuming it is already on the device
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","am","force-stop","io.appium.uiautomator2.server"]
[UiAutomator2] Starting uiautomator2 server v0.1.8
[UiAutomator2] Running command: 'adb -s 74a52861c958 shell am instrument -w io.appium.uiautomator2.server.test/android.support.test.runner.AndroidJUnitRunner'
[UiAutomator2] Waiting up to 20000ms for UiAutomator2 to be online...
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:4774/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:4774/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:4774/wd/hub/status] with no body
[debug] [JSONWP Proxy] Proxying [GET /status] to [GET http://localhost:4774/wd/hub/status] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\"value\":\"Status Invoked\",\"status\":0,\"sessionId\":\"SESSIONID\"}"
[debug] [JSONWP Proxy] Proxying [POST /session] to [POST http://localhost:4774/wd/hub/session] with body: {"desiredCapabilities":{"platform":"LINUX","webStorageEnabled":false,"takesScreenshot":true,"javascriptEnabled":true,"databaseEnabled":false,"networkConnectionEnabled":true,"locationContextEnabled":false,"warnings":{},"desired":{"appPackage":"com.jhqc.pxsj","appActivity":"com.jhqc.pxsj.activity.launch.LaunchActivity","udid":"74a52861c958","platformVersion":"4.4.4","platformName":"android","automationName":"uiautomator2","deviceName":"74a52861c958","noReset":true,"noSign":true,"unicodeKeyboard":true,"resetKeyboard":true,"systemPort":"4774"},"appPackage":"com.jhqc.pxsj","appActivity":"com.jhqc.pxsj.activity.launch.LaunchActivity","udid":"74a52861c958","platformVersion":"4.4.4","platformName":"android","automationName":"uiautomator2","deviceName":"74a52861c958","noReset":true,"noSign":true,"unicodeKeyboard":true,"resetKeyboard":true,"systemPort":"4774","deviceUDID":"74a52861c958","deviceScreenSize":"720x1280","deviceModel":"Che1-CL20","deviceManufacturer":"HUAWEI"}}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"Created Session","status":0,"sessionId":"73ab227a-31bb-41f0-8492-c1fdfe95174c"}
[UiAutomator2] UiAutomator2 did not start the activity we were waiting for, 'com.jhqc.pxsj/com.jhqc.pxsj.activity.launch.LaunchActivity'. Starting it ourselves
[debug] [ADB] Device API level: 19
[debug] [ADB] Getting connected devices...
[debug] [ADB] 1 device(s) connected
[debug] [ADB] Running 'F:\android-sdk_r24.4.1-windows\android-sdk-windows\platform-tools\adb.exe' with args: ["-P",5037,"-s","74a52861c958","shell","am","start","-W","-n","com.jhqc.pxsj/com.jhqc.pxsj.activity.launch.LaunchActivity","-S","-a","android.intent.action.MAIN","-c","android.intent.category.LAUNCHER","-f","0x10200000"]
[Appium] New AndroidUiautomator2Driver session created successfully, session 97457b5d-c529-4c18-afd9-376a7c4eed76 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1517387410888 (16:30:10 GMT+0800 (中国标准时间))
[debug] [MJSONWP] Responding to client with driver.createSession() result: {"appPackage":"com.jhqc.pxsj","appActivity":"com.jhqc.pxsj.activity.launch.LaunchActivity","udid":"74a52861c958","platformVersion":"4.4.4","platformName":"android","automationName":"uiautomator2","deviceName":"74a52861c958","noReset":"True","noSign":"True","unicodeKeyboard":"True","resetKeyboard":"True","systemPort":"4774"}
[HTTP] <-- POST /wd/hub/session 200 47622 ms - 397 
adb -s 74a52861c958 shell cat /system/build.prop 
Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
testLogin (TestCase.LoginTest.LoginTest) ... {'release': '4.4.4', 'model': 'Che1-CL20', 'brand': 'Honor', 'device': 'Che1'}
ERROR
ERROR
======================================================================
ERROR: testLogin (TestCase.LoginTest.LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:\Python36\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "E:\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "E:\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "E:\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "E:\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "E:\Python36\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "E:\Python36\lib\socket.py", line 722, in create_connection
    raise err
  File "E:\Python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PycharmProjects\psxj\TestCase\LoginTest.py", line 25, in testLogin
    page = Login(app)
  File "E:\PycharmProjects\psxj\PageObjects\LoginPage\LoginPage.py", line 13, in __init__
    self.page = pages.PagesObjects(_init)
  File "E:\PycharmProjects\psxj\PageObjects\pages.py", line 26, in __init__
    self.driver.launch_app()
  File "E:\Python36\lib\site-packages\appium\webdriver\webdriver.py", line 580, in launch_app
    self.execute(Command.LAUNCH_APP)
  File "E:\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "E:\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "E:\Python36\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 528, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "E:\Python36\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "E:\Python36\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "E:\Python36\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "E:\Python36\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "E:\Python36\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

**Comment by Louis-me** [comment]
server启动失败了，请问下你的appium什么版本的，我的是1.7.2的

**Comment by LYJHON** [comment]
1.7.1

发自我的 iPhone

**Comment by LYJHON** [comment]
我跟了哈，在driver哪里，url传进去请求的时候被U2拒绝了，为什么被拒绝，不晓得是不是U2服务器的原因

发自我的 iPhone

**Comment by LYJHON** [comment]
1.7.1的

发自我的 iPhone

**Comment by Louis-me** [comment]
重新试试。。。应该可以了，不行的话，关闭重新执行
